package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'DomumOrnamentum_PullRequests2_CommonBuildCounter'
in the project with id = 'DomumOrnamentum_PullRequests2', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum_PullRequests2"), BuildType({
    templates(RelativeId("CommonBuildCounter"))
    id("DomumOrnamentum_PullRequests2_CommonBuildCounter")
    name = "Common Build Counter"
    description = "Defines version numbers uniquely over all Pull Request builds"
}))

