package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'DomumOrnamentum_OfficialPublications_CommonB'
in the project with id = 'DomumOrnamentum_OfficialPublications', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum_OfficialPublications"), BuildType({
    templates(RelativeId("CommonBuildCounter"))
    id("DomumOrnamentum_OfficialPublications_CommonB")
    name = "Common Build Counter"
    description = "Represents the version counter within Minecolonies for official releases."
}))

