package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'DomumOrnamentum_PullRequests2_BuildAndTest'
in the project with id = 'DomumOrnamentum_PullRequests2', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum_PullRequests2"), BuildType({
    templates(RelativeId("BuildWithTesting"))
    id("DomumOrnamentum_PullRequests2_BuildAndTest")
    name = "Build and Test"
    description = "Builds and Tests the pull request."

    params {
        param("Project.Type", "mods")
        param("env.Version.Patch", "%dep.LetSDevTogether_DomumOrnamentum_PullRequests2_CommonBuildCounter.build.number%")
        param("env.Version.Suffix", "-PR")
    }

    dependencies {
        snapshot(RelativeId("DomumOrnamentum_PullRequests2_CommonBuildCounter")) {
            reuseBuilds = ReuseBuilds.NO
            onDependencyFailure = FailureAction.FAIL_TO_START
        }
    }
    
    disableSettings("BUILD_EXT_15")
}))

