package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Structurize_Branches_Common'
in the project with id = 'Structurize_Branches', and delete the patch script.
*/
create(RelativeId("Structurize_Branches"), BuildType({
    templates(RelativeId("CommonBuildCounter"))
    id("Structurize_Branches_Common")
    name = "Common Build Counter"
    description = "Tracks the amount of builds run for branches"
}))

