package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Structurize_UpgradeAlphaBeta_UpgradeAlphaBeta'
in the project with id = 'Structurize_UpgradeAlphaBeta', and delete the patch script.
*/
create(RelativeId("Structurize_UpgradeAlphaBeta"), BuildType({
    templates(RelativeId("Upgrade"))
    id("Structurize_UpgradeAlphaBeta_UpgradeAlphaBeta")
    name = "Upgrade - Alpha -> Beta"
    description = "Upgrades the current Alpha to Beta."

    params {
        param("Source.Branch", "version")
        param("Default.Branch", "testing/%Current Minecraft Version%")
        param("VCS.Branches", "+:refs/heads/testing/(*)")
        param("Target.Branch", "testing")
        param("env.Version", "%env.Version.Major%.%env.Version.Minor%.%build.counter%-BETA")
    }
    
    disableSettings("BUILD_EXT_9")
}))

