package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Structurize_Branches_Build'
in the project with id = 'Structurize_Branches', and delete the patch script.
*/
create(RelativeId("Structurize_Branches"), BuildType({
    templates(RelativeId("Build"))
    id("Structurize_Branches_Build")
    name = "Build"
    description = "Builds the branch without testing."

    params {
        param("Project.Type", "mods")
        param("env.Version.Patch", "%dep.LetSDevTogether_Structurize_Branches_Common.build.number%")
    }

    dependencies {
        snapshot(RelativeId("Structurize_Branches_Common")) {
            reuseBuilds = ReuseBuilds.NO
            onDependencyFailure = FailureAction.FAIL_TO_START
        }
    }
}))

