package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Structurize_UpgradeBetaRelease_UpgradeBetaRelease'
in the project with id = 'Structurize_UpgradeBetaRelease', and delete the patch script.
*/
create(RelativeId("Structurize_UpgradeBetaRelease"), BuildType({
    templates(RelativeId("Upgrade"))
    id("Structurize_UpgradeBetaRelease_UpgradeBetaRelease")
    name = "Upgrade Beta -> Release"
    description = "Upgrades the current Beta to Release."

    params {
        param("Source.Branch", "testing")
        param("Default.Branch", "release/%Current Minecraft Version%")
        param("VCS.Branches", "+:refs/heads/release/(*)")
        param("Target.Branch", "release")
        param("env.Version", "%env.Version.Major%.%env.Version.Minor%.%build.counter%-RELEASE")
    }
}))

