package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'DomumOrnamentum_UpgradeBetaRelease'
in the project with id = 'DomumOrnamentum', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum"), Project({
    id("DomumOrnamentum_UpgradeBetaRelease")
    name = "Upgrade Beta -> Release"
    description = "Upgrades the current Beta to Release"
}))

