package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'DomumOrnamentum_UpgradeAlphaBeta'
in the project with id = 'DomumOrnamentum', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum"), Project({
    id("DomumOrnamentum_UpgradeAlphaBeta")
    name = "Upgrade - Alpha -> Beta"
    description = "Updates the current alpha to beta."

    params {
        select("Current Minecraft Version", "1.16.3", label = "Current Minecraft Version",
                options = listOf("1.12", "1.13", "1.14", "1.15", "1.16", "1.17"))
    }
}))

