package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'DomumOrnamentum_OfficialPublications'
in the project with id = 'DomumOrnamentum', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum"), Project({
    id("DomumOrnamentum_OfficialPublications")
    name = "Official Publications"
    description = "Holds projects and builds related to official publications"
}))

