package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'DomumOrnamentum_Beta'
in the project with id = 'DomumOrnamentum', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum"), Project({
    id("DomumOrnamentum_Beta")
    name = "Beta"
    description = "Beta version builds of domum ornamentum"

    params {
        param("Default.Branch", "testing/%Current Minecraft Version%")
        param("VCS.Branches", "+:refs/heads/testing/(*)")
        param("env.CURSERELEASETYPE", "beta")
        param("env.Version.Suffix", "-BETA")
    }
}))

