package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'DomumOrnamentum_Release'
in the project with id = 'DomumOrnamentum', and delete the patch script.
*/
create(RelativeId("DomumOrnamentum"), Project({
    id("DomumOrnamentum_Release")
    name = "Release"
    description = "Beta version builds of domum ornamentum"

    params {
        param("Default.Branch", "release/%Current Minecraft Version%")
        param("VCS.Branches", "+:refs/heads/release/(*)")
        param("env.CURSERELEASETYPE", "release")
        param("env.Version.Suffix", "-RELEASE")
    }
}))

