package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Structurize_UpgradeAlphaBeta'
in the project with id = 'Structurize', and delete the patch script.
*/
create(RelativeId("Structurize"), Project({
    id("Structurize_UpgradeAlphaBeta")
    name = "Upgrade - Alpha -> Beta"
    description = "Updates the current alpha to beta."

    params {
        param("Current Minecraft Version", "1.16.3")
    }
}))

