package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Authentication_HttpsGithubComLdtteamAuthenticationGitRefsHeadsMaster'
in the project with id = 'Authentication', and delete the patch script.
*/
create(RelativeId("Authentication"), GitVcsRoot({
    id("Authentication_HttpsGithubComLdtteamAuthenticationGitRefsHeadsMaster")
    name = "https://github.com/ldtteam/authentication.git#refs/heads/master"
    url = "https://github.com/ldtteam/authentication.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
}))

