package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'MinecoloniesWebsite_HttpsGithubComLdtteamMinecoloniesWikiRefsHeadsMain'
in the project with id = 'MinecoloniesWebsite', and delete the patch script.
*/
create(RelativeId("MinecoloniesWebsite"), GitVcsRoot({
    id("MinecoloniesWebsite_HttpsGithubComLdtteamMinecoloniesWikiRefsHeadsMain")
    name = "https://github.com/ldtteam/MinecoloniesWiki#refs/heads/main"
    url = "https://github.com/ldtteam/MinecoloniesWiki"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "OrionDevelopment"
        password = "credentialsJSON:6131cd14-fa05-44e0-bcb6-d834103f967c"
    }
    param("useAlternates", "true")
}))

