package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Structurize_HttpsGithubComLdtteamStructurizeRefsHeadsVersionLatest'
in the project with id = 'Structurize', and delete the patch script.
*/
create(RelativeId("Structurize"), GitVcsRoot({
    id("Structurize_HttpsGithubComLdtteamStructurizeRefsHeadsVersionLatest")
    name = "https://github.com/ldtteam/Structurize#refs/heads/version/latest"
    url = "https://github.com/ldtteam/Structurize"
    branch = "refs/heads/version/latest"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "OrionDevelopment"
        password = "credentialsJSON:23cd3823-3e9f-4c80-a1c4-6ad9c876842a"
    }
}))

