package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = 'b4284ff6-778b-49f6-bc57-1c681bc93a3b'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("b4284ff6-778b-49f6-bc57-1c681bc93a3b"))

