package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '65324a29-0ed9-4e16-ab58-037b37fb2692'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("65324a29-0ed9-4e16-ab58-037b37fb2692"))

