package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '13662c45-8794-497a-8d03-45d5190a72b7'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("13662c45-8794-497a-8d03-45d5190a72b7"))

