package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '55e4cc72-0280-4728-9734-d9db1cb8b074'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("55e4cc72-0280-4728-9734-d9db1cb8b074"))

