package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '02596c29-26f2-4637-994d-b136fe434408'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("02596c29-26f2-4637-994d-b136fe434408"))

