package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = 'e4c0008d-5f73-4fbe-a025-f98a979523a4'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("e4c0008d-5f73-4fbe-a025-f98a979523a4"))

