package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '167564cd-1065-49d8-af78-60c3cfcf25f9'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("167564cd-1065-49d8-af78-60c3cfcf25f9"))

